development: &non_production_settings
  site_url: http://10.200.1.25/fam
  site_name: Famicles
  admin_email: joe@jnmsolutions.com
  
test:
  <<: *non_production_settings
  
production:
  site_url: http://www.example.com
  site_name: Bort
  admin_email: bort@bort.com
